#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright: (C) 2013 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import os
import shutil
import sys


def copy_data_file(filename, dest, dest_filename=''):
    '''copy filename to dest'''
    if dest_filename:
        dest = os.path.join(dest, dest_filename)
    shutil.copy(os.path.join(os.path.dirname(__file__), 'data', filename), dest)


if __name__ == '__main__':

    if os.environ.get("MOCK_ERROR_MODE") == "1":
        sys.stderr.write('error asked for rsync\n')
        sys.exit(1)

    commands = " ".join(sys.argv[1:])

    if commands == '--remove-source-files --timeout=60 rsync://default/cu2d_out/packagelist_rsync* .':
        copy_data_file('packagelist_rsync_foo-front', '.')
        copy_data_file('packagelist_rsync_oif-head', '.')
        sys.exit(0)
    elif commands == '--remove-source-files --timeout=60 rsync://nothing/cu2d_out/packagelist_rsync* .':
        sys.exit(0)

    # unhandled case
    sys.exit(1)
