#!/usr/bin/env python
# -*- coding: UTF8 -*-
# Copyright: (C) 2013 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import os
import shutil
import sys

if __name__ == '__main__':

    if sys.argv[1] == 'branch':

        if "SIMULATE_ERROR" in os.environ:
            sys.exit(1)

        origin_path = sys.argv[2]
        if len(sys.argv) < 4:
            dest_branch = origin_path.split('/')[-1]
        else:
            dest_branch = sys.argv[3]
        shutil.copytree(origin_path, dest_branch)

