#!/usr/bin/env python
# -*- coding: UTF8 -*-
# Copyright: (C) 2013 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import os
import sys


if __name__ == '__main__':

    if os.environ.get("MOCK_ERROR_MODE") == "1":
        sys.stderr.write('error in dput\n')
        sys.exit(1)

    command = " ".join(sys.argv[1:])
    if command == "ppa:didrocks/foo foo_83.09.13-0ubuntu1_source.changes":
        sys.exit(0)


    # unhandled case
    sys.exit(1)