#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright: (C) 2013 Canonical
#
# Authors:
#  Didier Roche
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import os
import shutil
import sys

def copy_data_file(filename, dest, dest_filename=None):
    '''copy filename to dest'''
    if dest_filename:
        dest = os.path.join(dest, dest_filename)
    shutil.copy(os.path.join(os.path.dirname(__file__), 'data', filename), dest)

if __name__ == '__main__':


    if os.environ.get("MOCK_ERROR_MODE") == "1":
        sys.exit(1)

    args = sys.argv
    command = " ".join(args[1:])
    if command.startswith("-E cowbuilder --execute"):
        # check we have two bindmounts
        if (sys.argv[1:].count("--bindmounts") != 2):
            sys.exit(1)

        if args[18] == "invalidkey":
            sys.exit(1)

        dest_dir = args[5]
        distro_version = args[20]
        serie = os.environ['DIST']

        # this mode should have the ppa call
        if os.environ.get("MOCK_MODE") == "1":
            if "--ppa ubuntu-unity/foo" in command:
                copy_data_file("foo_1.2-0ubuntu1_source.changes.lastcontent", dest_dir, dest_filename="foo_1.2-0ubuntu1_source.changes")
                sys.exit(0)

        else:
            if serie == "precise":
                copy_data_file("foo_1.2-0ubuntu1_source.changes.onprecise", dest_dir, dest_filename="foo_1.2-0ubuntu1_source.changes")
                sys.exit(0)
            elif serie == "raring":
                if distro_version == "1.1-0ubuntu1":
                    copy_data_file("foo_1.2-0ubuntu1_source.changes.lastcontent", dest_dir, dest_filename="foo_1.2-0ubuntu1_source.changes")
                    sys.exit(0)
                elif distro_version == "1.0-0ubuntu1":
                    copy_data_file("foo_1.2-0ubuntu1_source.changes.sincedistroversion", dest_dir, dest_filename="foo_1.2-0ubuntu1_source.changes")
                    sys.exit(0)

    # unhandled case
    sys.exit(1)
